# Generated by Django 2.2.16 on 2022-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_userauth_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='confirm_code',
            field=models.CharField(blank=True, max_length=150, verbose_name='Token'),
        ),
    ]
