# Generated by Django 2.2.16 on 2022-06-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220605_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='confirm_code',
        ),
    ]
