name: Yamdb Workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Запуск Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r api_yamdb/requirements.txt

      - name: Тесты flake8 и Django
        run: |
          python -m flake8
          cd api_yamdb/
          python manage.py test
